// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

// Protobuf Java Version: 3.25.5
package com.example.grpc.proto.bean;

public interface StreamResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.proto.StreamResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request_info = 1;</code>
   * @return The requestInfo.
   */
  java.lang.String getRequestInfo();
  /**
   * <code>string request_info = 1;</code>
   * @return The bytes for requestInfo.
   */
  com.google.protobuf.ByteString
      getRequestInfoBytes();
}
