// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

// Protobuf Java Version: 3.25.5
package com.example.grpc.proto.bean;

public interface StudentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.proto.StudentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 age = 1;</code>
   * @return The age.
   */
  int getAge();
}
