// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

// Protobuf Java Version: 3.25.5
package com.example.grpc.proto.bean;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.proto.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.example.grpc.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<com.example.grpc.proto.bean.StudentResponse> 
      getStudentResponseList();
  /**
   * <code>repeated .com.example.grpc.proto.StudentResponse studentResponse = 1;</code>
   */
  com.example.grpc.proto.bean.StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .com.example.grpc.proto.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .com.example.grpc.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends com.example.grpc.proto.bean.StudentResponseOrBuilder> 
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .com.example.grpc.proto.StudentResponse studentResponse = 1;</code>
   */
  com.example.grpc.proto.bean.StudentResponseOrBuilder getStudentResponseOrBuilder(
      int index);
}
