// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

// Protobuf Java Version: 3.25.5
package com.example.grpc.proto.bean;

/**
 * Protobuf type {@code com.example.grpc.proto.StudentResponseList}
 */
public final class StudentResponseList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.grpc.proto.StudentResponseList)
    StudentResponseListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StudentResponseList.newBuilder() to construct.
  private StudentResponseList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StudentResponseList() {
    studentResponseList_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new StudentResponseList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.grpc.proto.bean.Student.internal_static_com_example_grpc_proto_StudentResponseList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.grpc.proto.bean.Student.internal_static_com_example_grpc_proto_StudentResponseList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.grpc.proto.bean.StudentResponseList.class, com.example.grpc.proto.bean.StudentResponseList.Builder.class);
  }

  public static final int STUDENTRESPONSELIST_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.example.grpc.proto.bean.StudentResponse> studentResponseList_;
  /**
   * <code>repeated .com.example.grpc.proto.StudentResponse studentResponseList = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.example.grpc.proto.bean.StudentResponse> getStudentResponseListList() {
    return studentResponseList_;
  }
  /**
   * <code>repeated .com.example.grpc.proto.StudentResponse studentResponseList = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.example.grpc.proto.bean.StudentResponseOrBuilder> 
      getStudentResponseListOrBuilderList() {
    return studentResponseList_;
  }
  /**
   * <code>repeated .com.example.grpc.proto.StudentResponse studentResponseList = 1;</code>
   */
  @java.lang.Override
  public int getStudentResponseListCount() {
    return studentResponseList_.size();
  }
  /**
   * <code>repeated .com.example.grpc.proto.StudentResponse studentResponseList = 1;</code>
   */
  @java.lang.Override
  public com.example.grpc.proto.bean.StudentResponse getStudentResponseList(int index) {
    return studentResponseList_.get(index);
  }
  /**
   * <code>repeated .com.example.grpc.proto.StudentResponse studentResponseList = 1;</code>
   */
  @java.lang.Override
  public com.example.grpc.proto.bean.StudentResponseOrBuilder getStudentResponseListOrBuilder(
      int index) {
    return studentResponseList_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < studentResponseList_.size(); i++) {
      output.writeMessage(1, studentResponseList_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < studentResponseList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, studentResponseList_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.grpc.proto.bean.StudentResponseList)) {
      return super.equals(obj);
    }
    com.example.grpc.proto.bean.StudentResponseList other = (com.example.grpc.proto.bean.StudentResponseList) obj;

    if (!getStudentResponseListList()
        .equals(other.getStudentResponseListList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getStudentResponseListCount() > 0) {
      hash = (37 * hash) + STUDENTRESPONSELIST_FIELD_NUMBER;
      hash = (53 * hash) + getStudentResponseListList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.grpc.proto.bean.StudentResponseList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.proto.bean.StudentResponseList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.proto.bean.StudentResponseList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.proto.bean.StudentResponseList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.proto.bean.StudentResponseList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.proto.bean.StudentResponseList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.proto.bean.StudentResponseList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpc.proto.bean.StudentResponseList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.grpc.proto.bean.StudentResponseList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.grpc.proto.bean.StudentResponseList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.grpc.proto.bean.StudentResponseList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpc.proto.bean.StudentResponseList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.grpc.proto.bean.StudentResponseList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.grpc.proto.StudentResponseList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.grpc.proto.StudentResponseList)
      com.example.grpc.proto.bean.StudentResponseListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.grpc.proto.bean.Student.internal_static_com_example_grpc_proto_StudentResponseList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.grpc.proto.bean.Student.internal_static_com_example_grpc_proto_StudentResponseList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.grpc.proto.bean.StudentResponseList.class, com.example.grpc.proto.bean.StudentResponseList.Builder.class);
    }

    // Construct using com.example.grpc.proto.bean.StudentResponseList.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (studentResponseListBuilder_ == null) {
        studentResponseList_ = java.util.Collections.emptyList();
      } else {
        studentResponseList_ = null;
        studentResponseListBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.grpc.proto.bean.Student.internal_static_com_example_grpc_proto_StudentResponseList_descriptor;
    }

    @java.lang.Override
    public com.example.grpc.proto.bean.StudentResponseList getDefaultInstanceForType() {
      return com.example.grpc.proto.bean.StudentResponseList.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.grpc.proto.bean.StudentResponseList build() {
      com.example.grpc.proto.bean.StudentResponseList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.grpc.proto.bean.StudentResponseList buildPartial() {
      com.example.grpc.proto.bean.StudentResponseList result = new com.example.grpc.proto.bean.StudentResponseList(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.example.grpc.proto.bean.StudentResponseList result) {
      if (studentResponseListBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          studentResponseList_ = java.util.Collections.unmodifiableList(studentResponseList_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.studentResponseList_ = studentResponseList_;
      } else {
        result.studentResponseList_ = studentResponseListBuilder_.build();
      }
    }

    private void buildPartial0(com.example.grpc.proto.bean.StudentResponseList result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.grpc.proto.bean.StudentResponseList) {
        return mergeFrom((com.example.grpc.proto.bean.StudentResponseList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.grpc.proto.bean.StudentResponseList other) {
      if (other == com.example.grpc.proto.bean.StudentResponseList.getDefaultInstance()) return this;
      if (studentResponseListBuilder_ == null) {
        if (!other.studentResponseList_.isEmpty()) {
          if (studentResponseList_.isEmpty()) {
            studentResponseList_ = other.studentResponseList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureStudentResponseListIsMutable();
            studentResponseList_.addAll(other.studentResponseList_);
          }
          onChanged();
        }
      } else {
        if (!other.studentResponseList_.isEmpty()) {
          if (studentResponseListBuilder_.isEmpty()) {
            studentResponseListBuilder_.dispose();
            studentResponseListBuilder_ = null;
            studentResponseList_ = other.studentResponseList_;
            bitField0_ = (bitField0_ & ~0x00000001);
            studentResponseListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getStudentResponseListFieldBuilder() : null;
          } else {
            studentResponseListBuilder_.addAllMessages(other.studentResponseList_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.example.grpc.proto.bean.StudentResponse m =
                  input.readMessage(
                      com.example.grpc.proto.bean.StudentResponse.parser(),
                      extensionRegistry);
              if (studentResponseListBuilder_ == null) {
                ensureStudentResponseListIsMutable();
                studentResponseList_.add(m);
              } else {
                studentResponseListBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.example.grpc.proto.bean.StudentResponse> studentResponseList_ =
      java.util.Collections.emptyList();
    private void ensureStudentResponseListIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        studentResponseList_ = new java.util.ArrayList<com.example.grpc.proto.bean.StudentResponse>(studentResponseList_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.grpc.proto.bean.StudentResponse, com.example.grpc.proto.bean.StudentResponse.Builder, com.example.grpc.proto.bean.StudentResponseOrBuilder> studentResponseListBuilder_;

    /**
     * <code>repeated .com.example.grpc.proto.StudentResponse studentResponseList = 1;</code>
     */
    public java.util.List<com.example.grpc.proto.bean.StudentResponse> getStudentResponseListList() {
      if (studentResponseListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(studentResponseList_);
      } else {
        return studentResponseListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.example.grpc.proto.StudentResponse studentResponseList = 1;</code>
     */
    public int getStudentResponseListCount() {
      if (studentResponseListBuilder_ == null) {
        return studentResponseList_.size();
      } else {
        return studentResponseListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.example.grpc.proto.StudentResponse studentResponseList = 1;</code>
     */
    public com.example.grpc.proto.bean.StudentResponse getStudentResponseList(int index) {
      if (studentResponseListBuilder_ == null) {
        return studentResponseList_.get(index);
      } else {
        return studentResponseListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.example.grpc.proto.StudentResponse studentResponseList = 1;</code>
     */
    public Builder setStudentResponseList(
        int index, com.example.grpc.proto.bean.StudentResponse value) {
      if (studentResponseListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentResponseListIsMutable();
        studentResponseList_.set(index, value);
        onChanged();
      } else {
        studentResponseListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.proto.StudentResponse studentResponseList = 1;</code>
     */
    public Builder setStudentResponseList(
        int index, com.example.grpc.proto.bean.StudentResponse.Builder builderForValue) {
      if (studentResponseListBuilder_ == null) {
        ensureStudentResponseListIsMutable();
        studentResponseList_.set(index, builderForValue.build());
        onChanged();
      } else {
        studentResponseListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.proto.StudentResponse studentResponseList = 1;</code>
     */
    public Builder addStudentResponseList(com.example.grpc.proto.bean.StudentResponse value) {
      if (studentResponseListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentResponseListIsMutable();
        studentResponseList_.add(value);
        onChanged();
      } else {
        studentResponseListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.proto.StudentResponse studentResponseList = 1;</code>
     */
    public Builder addStudentResponseList(
        int index, com.example.grpc.proto.bean.StudentResponse value) {
      if (studentResponseListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentResponseListIsMutable();
        studentResponseList_.add(index, value);
        onChanged();
      } else {
        studentResponseListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.proto.StudentResponse studentResponseList = 1;</code>
     */
    public Builder addStudentResponseList(
        com.example.grpc.proto.bean.StudentResponse.Builder builderForValue) {
      if (studentResponseListBuilder_ == null) {
        ensureStudentResponseListIsMutable();
        studentResponseList_.add(builderForValue.build());
        onChanged();
      } else {
        studentResponseListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.proto.StudentResponse studentResponseList = 1;</code>
     */
    public Builder addStudentResponseList(
        int index, com.example.grpc.proto.bean.StudentResponse.Builder builderForValue) {
      if (studentResponseListBuilder_ == null) {
        ensureStudentResponseListIsMutable();
        studentResponseList_.add(index, builderForValue.build());
        onChanged();
      } else {
        studentResponseListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.proto.StudentResponse studentResponseList = 1;</code>
     */
    public Builder addAllStudentResponseList(
        java.lang.Iterable<? extends com.example.grpc.proto.bean.StudentResponse> values) {
      if (studentResponseListBuilder_ == null) {
        ensureStudentResponseListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, studentResponseList_);
        onChanged();
      } else {
        studentResponseListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.proto.StudentResponse studentResponseList = 1;</code>
     */
    public Builder clearStudentResponseList() {
      if (studentResponseListBuilder_ == null) {
        studentResponseList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        studentResponseListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.proto.StudentResponse studentResponseList = 1;</code>
     */
    public Builder removeStudentResponseList(int index) {
      if (studentResponseListBuilder_ == null) {
        ensureStudentResponseListIsMutable();
        studentResponseList_.remove(index);
        onChanged();
      } else {
        studentResponseListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.proto.StudentResponse studentResponseList = 1;</code>
     */
    public com.example.grpc.proto.bean.StudentResponse.Builder getStudentResponseListBuilder(
        int index) {
      return getStudentResponseListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.example.grpc.proto.StudentResponse studentResponseList = 1;</code>
     */
    public com.example.grpc.proto.bean.StudentResponseOrBuilder getStudentResponseListOrBuilder(
        int index) {
      if (studentResponseListBuilder_ == null) {
        return studentResponseList_.get(index);  } else {
        return studentResponseListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.example.grpc.proto.StudentResponse studentResponseList = 1;</code>
     */
    public java.util.List<? extends com.example.grpc.proto.bean.StudentResponseOrBuilder> 
         getStudentResponseListOrBuilderList() {
      if (studentResponseListBuilder_ != null) {
        return studentResponseListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(studentResponseList_);
      }
    }
    /**
     * <code>repeated .com.example.grpc.proto.StudentResponse studentResponseList = 1;</code>
     */
    public com.example.grpc.proto.bean.StudentResponse.Builder addStudentResponseListBuilder() {
      return getStudentResponseListFieldBuilder().addBuilder(
          com.example.grpc.proto.bean.StudentResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .com.example.grpc.proto.StudentResponse studentResponseList = 1;</code>
     */
    public com.example.grpc.proto.bean.StudentResponse.Builder addStudentResponseListBuilder(
        int index) {
      return getStudentResponseListFieldBuilder().addBuilder(
          index, com.example.grpc.proto.bean.StudentResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .com.example.grpc.proto.StudentResponse studentResponseList = 1;</code>
     */
    public java.util.List<com.example.grpc.proto.bean.StudentResponse.Builder> 
         getStudentResponseListBuilderList() {
      return getStudentResponseListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.grpc.proto.bean.StudentResponse, com.example.grpc.proto.bean.StudentResponse.Builder, com.example.grpc.proto.bean.StudentResponseOrBuilder> 
        getStudentResponseListFieldBuilder() {
      if (studentResponseListBuilder_ == null) {
        studentResponseListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.example.grpc.proto.bean.StudentResponse, com.example.grpc.proto.bean.StudentResponse.Builder, com.example.grpc.proto.bean.StudentResponseOrBuilder>(
                studentResponseList_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        studentResponseList_ = null;
      }
      return studentResponseListBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.example.grpc.proto.StudentResponseList)
  }

  // @@protoc_insertion_point(class_scope:com.example.grpc.proto.StudentResponseList)
  private static final com.example.grpc.proto.bean.StudentResponseList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.grpc.proto.bean.StudentResponseList();
  }

  public static com.example.grpc.proto.bean.StudentResponseList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StudentResponseList>
      PARSER = new com.google.protobuf.AbstractParser<StudentResponseList>() {
    @java.lang.Override
    public StudentResponseList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<StudentResponseList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StudentResponseList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.grpc.proto.bean.StudentResponseList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

